# Generated by Django 4.2.12 on 2024-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_choice_question_quiz_useranswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
