# Generated by Django 4.2.12 on 2024-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='is_archived'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=False, verbose_name='is_open'),
        ),
    ]
