# Generated by Django 4.2.12 on 2024-08-16 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_quiz_archived_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='auther',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
