# Generated by Django 4.2.12 on 2024-08-17 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_quiz_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='started',
        ),
        migrations.CreateModel(
            name='AtttemptedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
