# Generated by Django 4.2.12 on 2024-08-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_useranswer_answer_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtttemptedQuiz',
        ),
    ]
