# Generated by Django 4.2.12 on 2024-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_atttemptedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
