# Generated by Django 4.2.12 on 2024-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_score_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
