# Generated by Django 4.2.12 on 2024-08-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_question_points_quiz_points_alter_score_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='points',
        ),
    ]
