# Generated by Django 4.2.12 on 2024-08-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_quiz_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='attempts',
        ),
    ]
